[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"
no-cache = true

[deploy]
healthcheck.path = "/api/health"
healthcheck.interval = "30s"
healthcheck.timeout = "10s"
restartPolicy = "on-failure" 